
import { Playlist, Track, Episode } from './types';

export const MOCK_TRACKS: Track[] = [
  {
    id: '1',
    title: 'Neon Drift',
    artist: 'Lazerhawk',
    album: 'Redline',
    coverUrl: 'https://picsum.photos/seed/track1/400/400',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
    duration: 372,
    genre: 'Electronic',
    mood: 'Energetic',
    bpm: 120,
  },
  {
    id: '2',
    title: 'Midnight City',
    artist: 'M83',
    album: 'Hurry Up, We\'re Dreaming',
    coverUrl: 'https://picsum.photos/seed/track2/400/400',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
    duration: 425,
    genre: 'Pop',
    mood: 'Euphoric',
    bpm: 105,
  },
  {
    id: '3',
    title: 'Weightless',
    artist: 'Marconi Union',
    album: 'Weightless',
    coverUrl: 'https://picsum.photos/seed/track3/400/400',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
    duration: 344,
    genre: 'Ambient',
    mood: 'Focus',
    bpm: 60,
  },
  {
    id: '4',
    title: 'Aerodynamic',
    artist: 'Daft Punk',
    album: 'Discovery',
    coverUrl: 'https://picsum.photos/seed/track4/400/400',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3',
    duration: 302,
    genre: 'Electronic',
    mood: 'Energetic',
    bpm: 123,
  },
  {
    id: '5',
    title: 'Nujabes Tribute',
    artist: 'Marcus D',
    album: 'Melancholy Hope',
    coverUrl: 'https://picsum.photos/seed/track5/400/400',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3',
    duration: 240,
    genre: 'Hip Hop',
    mood: 'Chill',
    bpm: 85,
  },
  {
    id: '6',
    title: 'Blue In Green',
    artist: 'Miles Davis',
    album: 'Kind of Blue',
    coverUrl: 'https://picsum.photos/seed/track6/400/400',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3',
    duration: 337,
    genre: 'Jazz',
    mood: 'Chill',
    bpm: 60,
  },
  {
    id: '7',
    title: 'Gymnopédie No. 1',
    artist: 'Erik Satie',
    album: 'Gymnopédies',
    coverUrl: 'https://picsum.photos/seed/track7/400/400',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3',
    duration: 180,
    genre: 'Classical',
    mood: 'Focus',
    bpm: 50,
  },
  {
    id: '8',
    title: 'Shadowplay',
    artist: 'Joy Division',
    album: 'Unknown Pleasures',
    coverUrl: 'https://picsum.photos/seed/track8/400/400',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3',
    duration: 231,
    genre: 'Rock',
    mood: 'Dark',
    bpm: 130,
  },
  {
    id: '9',
    title: 'Starboy',
    artist: 'The Weeknd',
    album: 'Starboy',
    coverUrl: 'https://picsum.photos/seed/track9/400/400',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3',
    duration: 230,
    genre: 'Pop',
    mood: 'Dark',
    bpm: 186,
  },
  {
    id: '10',
    title: 'Resonance',
    artist: 'Home',
    album: 'Odyssey',
    coverUrl: 'https://picsum.photos/seed/track10/400/400',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3',
    duration: 212,
    genre: 'Electronic',
    mood: 'Focus',
    bpm: 110,
  },
  {
    id: '11',
    title: 'Vanilla Drift',
    artist: 'Lofi Girl',
    album: 'Morning Study',
    coverUrl: 'https://picsum.photos/seed/track11/400/400',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3',
    duration: 156,
    genre: 'Hip Hop',
    mood: 'Focus',
    bpm: 80,
  },
  {
    id: '12',
    title: 'Time',
    artist: 'Pink Floyd',
    album: 'Dark Side of the Moon',
    coverUrl: 'https://picsum.photos/seed/track12/400/400',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3',
    duration: 413,
    genre: 'Rock',
    mood: 'Dark',
    bpm: 120,
  }
];

export const MOCK_PLAYLISTS: Playlist[] = [
  {
    id: 'p1',
    name: 'Daily Cortex Mix',
    description: 'Hyper-personalized for your morning flow.',
    coverUrl: 'https://picsum.photos/seed/p1/400/400',
    type: 'daily',
    tracks: MOCK_TRACKS,
  },
  {
    id: 'p2',
    name: 'Focus Flow',
    description: 'A deep dive into ambient and lofi textures.',
    coverUrl: 'https://picsum.photos/seed/p2/400/400',
    type: 'mood',
    tracks: [MOCK_TRACKS[2]],
  },
  {
    id: 'p3',
    name: 'Weekly Discovery',
    description: 'Fresh tracks picked by the AI engine.',
    coverUrl: 'https://picsum.photos/seed/p3/400/400',
    type: 'weekly',
    tracks: MOCK_TRACKS,
  },
  {
    id: 'p4',
    name: 'Late Night Synthesis',
    description: 'Chill synth textures for the evening.',
    coverUrl: 'https://picsum.photos/seed/p4/400/400',
    type: 'custom',
    tracks: [MOCK_TRACKS[0]],
  },
];

export const MOCK_EPISODES: Episode[] = [
  {
    id: 'ep-1',
    title: 'The AI Renaissance & Synth Minds',
    artist: 'Dr. Aris Thorne',
    showName: 'Cortex Broadcasts',
    publishDate: 'June 28, 2026',
    description: 'An exploration of neural intelligence merging with acoustic soundscapes. We discuss how machine learning recreates emotional resonances in electronic music, the future of automated curation, and what it means to create sound under the Cortex engine.',
    album: 'Cortex Talks',
    coverUrl: 'https://picsum.photos/seed/ep1/400/400',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-13.mp3',
    duration: 540,
    genre: 'AI Talk',
    mood: 'Focus',
    bpm: 90,
  },
  {
    id: 'ep-2',
    title: 'Cyber Dreams & Virtual Realities',
    artist: 'Luna Vance',
    showName: 'Synthesized Minds',
    publishDate: 'June 25, 2026',
    description: 'How does virtual architecture inspire cyberpunk tracks? Luna Vance hosts a discussion with guest synth-scenographers about retrofuturism, neo-tokyo aesthetics, and translating geometric wireframes into multi-dimensional ambient delay lines.',
    album: 'Synthesized Chronicles',
    coverUrl: 'https://picsum.photos/seed/ep2/400/400',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-14.mp3',
    duration: 480,
    genre: 'Cyber Culture',
    mood: 'Chill',
    bpm: 75,
  },
  {
    id: 'ep-3',
    title: 'Retro Synthwave Legacy & Beats',
    artist: 'DJ Redline',
    showName: 'Redline Radio Talk',
    publishDate: 'June 18, 2026',
    description: 'Throwback to the analog machines of the 80s that laid the bedrock for today\'s high-fidelity synthwave movement. DJ Redline breaks down classic drum machine samples, pulse waves, and the magic of analog tape saturation.',
    album: 'Retro Chronicles',
    coverUrl: 'https://picsum.photos/seed/ep3/400/400',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-15.mp3',
    duration: 620,
    genre: 'Retro Talk',
    mood: 'Energetic',
    bpm: 110,
  },
];
